### ISSUE TITLE
maple 0.3.0 breaks .files

### ISSUE THREAD

**Issue by lordnox** [mikeal/tako#31]
I had a simple static fileserver, just like in the example:

```
tako = require('tako');
app = tako();
app.route('*').files(require('path').join(__dirname, 'public'));
app.httpServer.listen(9999);
```

The query for something...

```
  curl localhost:9999/something.txt
```

... will now be redirected to...

```
  ./public/something.txt/
```

... and not obviously not found there.

I changed the mapleTree version from \* to 0.2.x to fix this.

**Comment by saambarati** [comment]
This is no longer broken in 0.3.x. 
I broke it when I first updated to 0.3.0 then fixed it a day later. Sorry about that.
